pipeline{
  agent any
  stages{

    stage("build"){
      echo "building app..."
    }
    stage("test"){
      echo "testing app..."
    }
    stage("deploy"){
      echo "deploying app..."
    }
  }
}
