version : '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
      - MYSQL_DATABASE=team-member-projects
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - 8083:80
volumes:
  mysql-data:
    driver: local


